"""
MeetingMind - Exporter
Generates PDF, Markdown, and plain text exports of meeting notes.
"""

import io
import textwrap
from datetime import datetime
from typing import Optional

try:
    from fpdf import FPDF, XPos, YPos
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False


def format_duration(seconds: float) -> str:
    """Format seconds into human-readable duration."""
    if seconds <= 0:
        return "Unknown"
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    if hours > 0:
        return f"{hours}h {minutes}m {secs}s"
    elif minutes > 0:
        return f"{minutes}m {secs}s"
    return f"{secs}s"


def to_markdown(meeting: dict) -> str:
    """
    Export meeting data to Markdown format.
    """
    notes = meeting.get("notes", {})
    created_at = meeting.get("created_at", "")
    try:
        dt = datetime.fromisoformat(created_at)
        date_str = dt.strftime("%B %d, %Y at %I:%M %p")
    except (ValueError, TypeError):
        date_str = created_at or "Unknown date"

    lines = []

    # Header
    lines.append(f"# {meeting.get('title', 'Meeting Notes')}")
    lines.append("")
    lines.append(f"**Date:** {date_str}")
    lines.append(f"**File:** {meeting.get('file_name', 'N/A')}")
    lines.append(f"**Duration:** {format_duration(meeting.get('duration', 0))}")
    lines.append(f"**Word Count:** {meeting.get('word_count', 0):,}")
    lines.append(f"**Language:** {meeting.get('language', 'en').upper()}")
    lines.append(f"**Meeting Type:** {notes.get('meeting_type', 'Other')}")
    lines.append(f"**Sentiment:** {notes.get('sentiment', 'Neutral')}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Summary
    lines.append("## Meeting Summary")
    lines.append("")
    for bullet in notes.get("summary", []):
        lines.append(f"- {bullet}")
    lines.append("")

    # Key Decisions
    decisions = notes.get("key_decisions", [])
    if decisions:
        lines.append("## Key Decisions Made")
        lines.append("")
        for decision in decisions:
            lines.append(f"- {decision}")
        lines.append("")

    # Action Items
    action_items = notes.get("action_items", [])
    if action_items:
        lines.append("## Action Items")
        lines.append("")
        lines.append("| Task | Assignee | Deadline | Priority |")
        lines.append("|------|----------|----------|----------|")
        for item in action_items:
            if isinstance(item, dict):
                task = item.get("task", "")
                assignee = item.get("assignee", "TBD")
                deadline = item.get("deadline", "Not specified")
                priority = item.get("priority", "Medium")
                lines.append(f"| {task} | {assignee} | {deadline} | {priority} |")
            else:
                lines.append(f"| {item} | TBD | Not specified | Medium |")
        lines.append("")

    # Discussion Topics
    topics = notes.get("discussion_topics", [])
    if topics:
        lines.append("## Discussion Topics")
        lines.append("")
        for topic in topics:
            lines.append(f"- {topic}")
        lines.append("")

    # Follow-up Items
    followups = notes.get("follow_up_items", [])
    if followups:
        lines.append("## Follow-up Items")
        lines.append("")
        for item in followups:
            lines.append(f"- [ ] {item}")
        lines.append("")

    # Full Transcript
    lines.append("## Full Transcript")
    lines.append("")
    formatted_transcript = meeting.get("formatted_transcript", meeting.get("transcript", ""))
    lines.append(formatted_transcript)
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by MeetingMind*")

    return "\n".join(lines)


def to_plain_text(meeting: dict) -> str:
    """
    Export meeting data to plain text format.
    """
    notes = meeting.get("notes", {})
    created_at = meeting.get("created_at", "")
    try:
        dt = datetime.fromisoformat(created_at)
        date_str = dt.strftime("%B %d, %Y at %I:%M %p")
    except (ValueError, TypeError):
        date_str = created_at or "Unknown date"

    width = 72
    separator = "=" * width
    thin_sep = "-" * width

    lines = []
    lines.append(separator)
    title = meeting.get("title", "Meeting Notes")
    lines.append(title.center(width))
    lines.append(separator)
    lines.append("")
    lines.append(f"Date:         {date_str}")
    lines.append(f"File:         {meeting.get('file_name', 'N/A')}")
    lines.append(f"Duration:     {format_duration(meeting.get('duration', 0))}")
    lines.append(f"Word Count:   {meeting.get('word_count', 0):,}")
    lines.append(f"Language:     {meeting.get('language', 'en').upper()}")
    lines.append(f"Meeting Type: {notes.get('meeting_type', 'Other')}")
    lines.append(f"Sentiment:    {notes.get('sentiment', 'Neutral')}")
    lines.append("")

    def section(title_text):
        lines.append(thin_sep)
        lines.append(f"  {title_text}")
        lines.append(thin_sep)

    # Summary
    section("MEETING SUMMARY")
    for bullet in notes.get("summary", []):
        wrapped = textwrap.fill(f"• {bullet}", width=width, subsequent_indent="  ")
        lines.append(wrapped)
    lines.append("")

    # Key Decisions
    decisions = notes.get("key_decisions", [])
    if decisions:
        section("KEY DECISIONS MADE")
        for d in decisions:
            wrapped = textwrap.fill(f"• {d}", width=width, subsequent_indent="  ")
            lines.append(wrapped)
        lines.append("")

    # Action Items
    action_items = notes.get("action_items", [])
    if action_items:
        section("ACTION ITEMS")
        for i, item in enumerate(action_items, 1):
            if isinstance(item, dict):
                task = item.get("task", "")
                assignee = item.get("assignee", "TBD")
                deadline = item.get("deadline", "Not specified")
                priority = item.get("priority", "Medium")
                lines.append(f"  {i}. {task}")
                lines.append(f"     Assignee: {assignee}  |  Deadline: {deadline}  |  Priority: {priority}")
            else:
                lines.append(f"  {i}. {item}")
        lines.append("")

    # Discussion Topics
    topics = notes.get("discussion_topics", [])
    if topics:
        section("DISCUSSION TOPICS")
        for topic in topics:
            wrapped = textwrap.fill(f"• {topic}", width=width, subsequent_indent="  ")
            lines.append(wrapped)
        lines.append("")

    # Follow-up Items
    followups = notes.get("follow_up_items", [])
    if followups:
        section("FOLLOW-UP ITEMS")
        for item in followups:
            wrapped = textwrap.fill(f"[ ] {item}", width=width, subsequent_indent="    ")
            lines.append(wrapped)
        lines.append("")

    # Full Transcript
    section("FULL TRANSCRIPT")
    formatted_transcript = meeting.get("formatted_transcript", meeting.get("transcript", ""))
    lines.append(formatted_transcript)
    lines.append("")

    lines.append(separator)
    lines.append("Generated by MeetingMind".center(width))
    lines.append(separator)

    return "\n".join(lines)


def _safe_latin1(text: str) -> str:
    """
    Replace characters that can't be encoded in latin-1 (used by built-in PDF fonts)
    with ASCII equivalents or '?'.
    """
    replacements = {
        "\u2014": "--",   # em dash
        "\u2013": "-",    # en dash
        "\u2018": "'",    # left single quote
        "\u2019": "'",    # right single quote
        "\u201C": '"',    # left double quote
        "\u201D": '"',    # right double quote
        "\u2022": "*",    # bullet (we override this in bullet_item)
        "\u2026": "...",  # ellipsis
        "\u2610": "[ ]",  # ballot box
        "\u25B8": ">",    # right-pointing triangle
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    # Final fallback: encode to latin-1, replacing remaining unknowns
    return text.encode("latin-1", errors="replace").decode("latin-1")


class _PDF(FPDF):
    """Custom FPDF subclass with header/footer for MeetingMind."""

    def __init__(self, title: str = "Meeting Notes"):
        super().__init__()
        self._doc_title = _safe_latin1(title)

    def header(self):
        # Purple header bar
        self.set_fill_color(124, 58, 237)   # #7C3AED
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 4)
        self.cell(0, 10, "MeetingMind", align="L")
        self.set_xy(0, 4)
        self.cell(200, 10, self._doc_title[:60], align="C")
        self.set_text_color(0, 0, 0)
        self.ln(14)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by MeetingMind", align="C")
        self.set_text_color(0, 0, 0)

    def section_title(self, text: str):
        self.set_fill_color(240, 237, 255)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(88, 28, 163)
        self.cell(0, 9, f"  {_safe_latin1(text)}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def bullet_item(self, text: str, indent: int = 5):
        self.set_font("Helvetica", "", 10)
        self.set_x(self.get_x() + indent)
        safe = _safe_latin1(text)
        self.multi_cell(0, 6, f"*  {safe}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def action_item_row(self, task: str, assignee: str, deadline: str, priority: str, idx: int):
        colors = {
            "High": (239, 68, 68),
            "Medium": (234, 179, 8),
            "Low": (34, 197, 94),
        }
        badge_color = colors.get(priority, (100, 100, 100))

        self.set_font("Helvetica", "B", 9)
        self.cell(0, 6, f"  {idx}. {_safe_latin1(task)}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        self.set_font("Helvetica", "", 9)
        self.set_text_color(80, 80, 80)
        self.set_x(self.get_x() + 10)
        self.cell(50, 5, f"Assignee: {_safe_latin1(assignee)}")
        self.cell(60, 5, f"Deadline: {_safe_latin1(deadline)}")

        # Priority badge
        self.set_fill_color(*badge_color)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 8)
        self.cell(25, 5, f" {priority} ", fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(7)

    def add_safe_text(self, text: str, font_size: int = 10):
        """Add text safely, handling encoding issues."""
        self.set_font("Helvetica", "", font_size)
        self.multi_cell(0, 5, _safe_latin1(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def to_pdf(meeting: dict) -> bytes:
    """
    Export meeting data to PDF. Returns PDF bytes.
    Raises ImportError if fpdf2 is not installed.
    """
    if not FPDF_AVAILABLE:
        raise ImportError(
            "fpdf2 is not installed. Run: pip install fpdf2"
        )

    notes = meeting.get("notes", {})
    title = meeting.get("title", "Meeting Notes")

    created_at = meeting.get("created_at", "")
    try:
        dt = datetime.fromisoformat(created_at)
        date_str = dt.strftime("%B %d, %Y at %I:%M %p")
    except (ValueError, TypeError):
        date_str = created_at or "Unknown date"

    pdf = _PDF(title=title)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title block
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(88, 28, 163)
    pdf.multi_cell(0, 10, _safe_latin1(title), align="C")
    pdf.ln(2)

    # Metadata row
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    meta_parts = [
        f"Date: {_safe_latin1(date_str)}",
        f"Duration: {format_duration(meeting.get('duration', 0))}",
        f"Words: {meeting.get('word_count', 0):,}",
        f"Type: {notes.get('meeting_type', 'Other')}",
        f"Sentiment: {notes.get('sentiment', 'Neutral')}",
    ]
    pdf.cell(0, 6, "  |  ".join(meta_parts), align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # Divider
    pdf.set_draw_color(124, 58, 237)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Summary
    pdf.section_title("Meeting Summary")
    for bullet in notes.get("summary", []):
        pdf.bullet_item(bullet)
    pdf.ln(4)

    # Key Decisions
    decisions = notes.get("key_decisions", [])
    if decisions:
        pdf.section_title("Key Decisions Made")
        for decision in decisions:
            pdf.bullet_item(decision)
        pdf.ln(4)

    # Action Items
    action_items = notes.get("action_items", [])
    if action_items:
        pdf.section_title("Action Items")
        for i, item in enumerate(action_items, 1):
            if isinstance(item, dict):
                pdf.action_item_row(
                    task=item.get("task", ""),
                    assignee=item.get("assignee", "TBD"),
                    deadline=item.get("deadline", "Not specified"),
                    priority=item.get("priority", "Medium"),
                    idx=i,
                )
            else:
                pdf.bullet_item(str(item))
        pdf.ln(4)

    # Discussion Topics
    topics = notes.get("discussion_topics", [])
    if topics:
        pdf.section_title("Discussion Topics")
        for topic in topics:
            pdf.bullet_item(topic)
        pdf.ln(4)

    # Follow-up Items
    followups = notes.get("follow_up_items", [])
    if followups:
        pdf.section_title("Follow-up Items")
        for item in followups:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_x(pdf.get_x() + 5)
            pdf.multi_cell(0, 6, f"[ ]  {_safe_latin1(item)}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(4)

    # Full Transcript (new page)
    pdf.add_page()
    pdf.section_title("Full Transcript")
    pdf.set_font("Courier", "", 8)
    pdf.set_text_color(40, 40, 40)

    formatted_transcript = meeting.get("formatted_transcript", meeting.get("transcript", ""))
    # Truncate if extremely long
    max_chars = 50000
    if len(formatted_transcript) > max_chars:
        formatted_transcript = formatted_transcript[:max_chars] + "\n\n[Transcript truncated for PDF export]"

    for line in formatted_transcript.split("\n"):
        try:
            pdf.cell(0, 4, _safe_latin1(line), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        except Exception:
            pdf.cell(0, 4, "[encoding error]", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_text_color(0, 0, 0)

    # Return bytes
    return bytes(pdf.output())
